server:
  port: 8301
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    base-path: /management #requires port
    port: 9301
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: Webflux app without contextpath with admincontextpath
