server:
  port: 8201
  servlet:
    context-path: /myContextPath
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    base-path: /management #requires port
    port: 9201
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: Servlet app with contextpath and admincontextpath