server:
  port: 8400
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: Webflux app with contextpath
  webflux:
    base-path: /myContextPath