server:
  port: 8100
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: Servlet app without contextpath