server:
  port: 8300
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: Webflux app without contextpath
